# Vahendid

Tabelis \@ref(tab:optics) leheküljel `r render_pageref(reference = "tab:optics")` on loodusteaduste klubi ja õppesessioonide jaoks osta tulevate vahendite nimekiri.

\onecolumn

(ref:koolile) Praktikal[@koolile]
(ref:globisens) insplay[@globisens]
(ref:globisens-science) insplay[@globisens_science]
(ref:globisens-CO2) insplay[@globisens_CO2]
(ref:globisens-O2) insplay[@globisens_O2]
(ref:globisens-chemical-biology) insplay[@globisens_chemical_biology]
(ref:globisens-physics) insplay[@globisens_physics]
(ref:globisens-force-acceleration) insplay[@globisens_force_acceleration]
(ref:globisens-breathing) insplay[@globisens_breathing]
(ref:globisens-magnetic-field) insplay[@globisens_magnetic_field]
(ref:globisens-photo-gate) insplay[@globisens_photo_gate]
(ref:muaket) Amazon.de[@muaket]
(ref:original) Drinkingbirdstore[@original]
(ref:set) Drinkingbirdstore[@set]
(ref:mahlapressidee-316) MAHLAPRESSID.ee[@mahlapressidee_316]
(ref:rods) forschool[@rods]
(ref:spintronics) UPPERSTORY[@spintronics]
(ref:noauthor-undated-jz) ebay[@noauthor_undated-jz]
(ref:laboratory) Amazon.de[@laboratory]
(ref:kg-salzsure) KREMER PIGMENTE[@kg_salzsure]
(ref:naatriumhdroksiid) Nord Reahim[@naatriumhdroksiid]
(ref:noauthor-undated-ec) Buddeberg[@noauthor_undated-ec]
(ref:totaledu-stand) Totaledu[@totaledu_stand]
(ref:aluminiumbrettenklemme) Amazon.de[@aluminiumbrettenklemme]
(ref:Reboot-undated-ke) Totaledu[@Reboot_undated-ke]
(ref:totaledu-phenolphtalein) Totaledu[@totaledu_phenolphtalein]
(ref:totaledu-litmus) Totaledu[@totaledu_litmus]
(ref:totaledu-universal-indicator) Totaledu[@totaledu_universal_indicator]
(ref:vvelhape) Nord Reahim[@vvelhape]

```{r label = "optics", echo=FALSE}
name <- c(
  "Valgusõpetuse üksikkomplekt",
  "Soojus- ja elektriõpetuse üksikkomplekt",
  "Mehaanika üksikkomplekt",
  "\\textbf{Globisens Labdisc: Keskkond}",
  "Globisens Labdisc: Teadus",
  "Globisens CO2 andur",
  "Globisens lahustunud hapniku elektrood",
  "Globisens Labdisc: Keemiline bioloogia",
  "Globisens Labdisc: Füüsika",
  "Globisens juhtmevaba jõu- ja kiirendusandur Dymo",
  "Globisens hingamisandur",
  "Globisens magnetvälja andur",
  "Globisens fotovärav",
  "Muaket Fine Scale, 50 g / 0.001 g Fine Scale, Electronic Digital Scales with LCD Display, Professional Milligram Scale, Pocket Scale, Laboratory Scale, Gold Scale, Letter Scale, MG Scales",
  "Original drinking bird",
  "Set of 4 hand boilers",
  "316 roostevaba terasest esmaklassiline veedestillaator Rainboy Sealion klaasist karahviniga",
  "RODS PLUS with Magnet Board (Ray Optics Demonstration Set PLUS)",
  "Spintronics Act One, Act Two, \\& Power Pack",
  "Japsin Sling Psychrometer Whirling Hygrometer Thermometer Plastic Body in °C/°F",
  "\\textbf{Laboratory Magnetic Stirrer Heating Plate 135 mm 100-1500 rpm 280°C 5L LED Display Magnetic Stirrer Mixer Magnetic Mixer with PT1000 Sensor with Holder EU Plug 5000 ml}",
  "\\textbf{Salzsäure 37 \\%}",
  "\\textbf{Naatriumhüdroksiid}",
  "\\textbf{Büretten mit geradem Hahn, Borosilikatglas 3.3, Klasse AS}",
  "\\textbf{Statiiv laborisse 50cm, lisadega}",
  "\\textbf{Aluminium-Bürettenklemme, Zubehör-Clip, Dual-Büretten-Zubehör, Büretten-Clip, Titrationsständer, Zubehör-Halter, Aluminium-Clip, Titrations-Clip, Aluminium-Gummi-Bürettenklemmen}",
  "\\textbf{Metüüloranži lahused 12x25ml}",
  "\\textbf{Fenoolftaleiin lahus 0,09\\% 12x25ml hoidekarbis}",
  "\\textbf{Lakmus indikaatorlahused 12x25ml}",
  "\\textbf{Universaalindikaatori lahused pH 1-12 hoidekarbis (12x25ml)}",
  "\\textbf{Väävelhape}"
)                  # 1

price <- c(
  119,
  299,
  159,
  478.9,
  478.9,
  268.9,
  218.9,
  707.9,
  646.9,
  308.9,
  149.9,
  61.9,
  42.9,
  19.99 + 9.56,
  10,
  22,
  299,
  340.62,
  178.3,
  42.89,
  329.99 + 18.94,
  13.51 + 19,
  4.2 * 1.2,
  104.48,
  51,
  9.99 + 7.5,
  57.6,
  56.4,
  61.2,
  70.8,
  10 * 1.2
)  # 2

source <- c(
  "(ref:koolile)",
  "(ref:koolile)",
  "(ref:koolile)",
  "(ref:globisens)",
  "(ref:globisens-science)",
  "(ref:globisens-CO2)",
  "(ref:globisens-O2)",
  "(ref:globisens-chemical-biology)",
  "(ref:globisens-physics)",
  "(ref:globisens-force-acceleration)",
  "(ref:globisens-breathing)",
  "(ref:globisens-magnetic-field)",
  "(ref:globisens-photo-gate)",
  "(ref:muaket)",
  "(ref:original)",
  "(ref:set)",
  "(ref:mahlapressidee-316)",
  "(ref:rods)",
  "(ref:spintronics)",
  "(ref:noauthor-undated-jz)",
  "(ref:laboratory)",
  "(ref:kg-salzsure)",
  "(ref:kg-natriumhydroxid)",
  "(ref:noauthor-undated-ec)",
  "(ref:totaledu-stand)",
  "(ref:aluminiumbrettenklemme)",
  "(ref:Reboot-undated-ke)",
  "(ref:totaledu-phenolphtalein)",
  "(ref:totaledu-litmus)",
  "(ref:totaledu-universal-indicator)",
  "(ref:vvelhape)"
)
                                                                                                  # 3
data_frame_of_tools <- data.frame(                                                           # 4
  name,                                                                                          # 5
  price,
  source # 6
)                                                                                                 # 7
                                                                                                  # 8
colnames(data_frame_of_tools) <- c(                                                          # 9
  "Nimi",                                                         # 10
  "$\\frac{\\text{Hind}}{€}$",
  "Allikas" # 11
)                                                     
# 12
librarian::shelf(c(
  "janitor"
))
data_frame_of_tools_with_total <- adorn_totals(dat = data_frame_of_tools, where = "row", fill = "", na.rm = TRUE, name = "Kokku", c(`$\\frac{\\text{Hind}}{€}$`))

librarian::shelf(c(
  "kableExtra"
))

print_table(                                                                                     # 14
  table = data_frame_of_tools_with_total,                                                              # 15
  caption = "Augustis 2023 \\textit{Edu Valemisse} soetatavad loodusteaduste õpetamise vahendid."                       # 16
)  %>%                                          # 4
  row_spec(nrow(data_frame_of_tools), hline_after = TRUE) %>%
  column_spec(1, width = "32em") %>%
  landscape()

```

\twocolumn

1. *Globisens Labdisc: Keskkond*[@globisens].

2. *Globisens Labdisc: Teadus*[@globisens_science].

3. *Globisens CO2 andur*[@globisens_CO2].

4. *Globisens lahustunud hapniku elektrood*[@globisens_O2].

5. *Globisens Labdisc: Keemiline bioloogia*[@globisens_chemical_biology].

6. *Globisens Labdisc: Füüsika*[@globisens_physics].

7. *Globisens juhtmevaba jõu- ja kiirendusandur Dymo*[@globisens_force_acceleration].

8. *Globisens hingamisandur*[@globisens_breathing].

9. *Globisens magnetvälja andur*[@globisens_magnetic_field].

10. *Globisens fotovärav*[@globisens_photo_gate].

11. *WA PCB 350-3 Laborwaage, digital, bis 350 g*[@teamwebmasterreicheltde_wa].

12. *Geomeetrilise optika komplekt II, 3-kiirelise laseriga, horisontaalne*[@totaledu_laser].

13. *Pipetitäitja 10ml*[@totaledu_filler].

14. *Võrdse massiga kehad, 6 tk*[@totaledu_equal_mass].

15. *Laborikittel, erinevad suurused*[@totaledu_clothing].

16. *Skalpell, ühes tükis*[@totaledu_scalpel].

17. *Statiiv laborisse 50cm, lisadega*[@totaledu_stand].

18. *Vaakumkuppel pumbaga*[@totaledu_vacuum_pump].

2. Vernier.

3. Pasco.

4. Sigma Aldrich.

5. Totaledu.

6. *Fluke 115 Compact True-Rms Digital Multimeter*[@fluke].

7. *Fluke 117 Multimeter for Electrician, Electrician Multimeter and Clamp Meter Combo Kit, 1 & Peak Tech P 8200 - Measuring Accessories Set for Digital Multimeter - 14 Pieces Including Bag*[@fluke-117].

8. *Kedelak GFCI Socket Tester with Voltage Display 90-250V Socket Tester Automatic Circuit Polarity Voltage Detector Breaker Finder HT107D*[@kedelak].

9. *BMK Energy Cost Meter, Power Meter with Overload Protection, 3680 W, Plug with large LCD screen, blue*[@bmk].

10. *DLYFULL LCD Universal Battery Tester for AA, AAA, C, D, 9V Digital Tester Battery Tester for CR123A, CR2, CRV3, 2CR5, CRP2 Battery Tester for 1.5V and 3V Button Cells (Red)*[@dlyfull].

11. *goobay Fixpoint 45246 Desoldering Braid 2 mm for Removal of Solder Wire on Soldering Points 1.5 m Pack of 1*[@goobay].

12. *BOJACK 50 g Soldering Paste No-Clean Lead-Free Flux Environmentally Friendly Soldering Tin Paste for Welding (Pack of 1)*[@bojack].

13. *MC POWER - Silicone soldering mat, LM-18, large flexible soldering mat, 55 x 35 cm, welding repair pad, heat-resistant up to 500 °C, anti-static, wipeable and rollable*[@mc].

14. *Preciva Soldering Station 200 ~ 480°C Soldering Iron Set with Soldering Vapour Extraction Including 2 Attachable Helping Hands 5 Additional Soldering Tips Standby Mode Soldering Set for Hobby Soldering*[@preciva].

15. *Flexible Helping Hands, Third Hand Soldering Aid, Soldering Station Tool, 6 x Flexible Helping Hands – One More Backup, Non-Slip Aluminium Base, Built-in Bowls, Heat-Resistant Cover*[@flexible].

16. *Wowgo Soldering Iron Set, 24 Pieces, 60 W Welding Tools, Electric Soldering Set with 5 Interchangeable Tips, Adjustable Temperature, Digital Multimeter, Soldering Iron Stand, Desoldering Pump, Portable Tool Bag*[@wowgo].

17. *Original drinking bird*[@original].

18. *Set of 4 hand boilers*[@set].

10. Arduino.

19. *Digitaalne pulktermomeeter, tehasesertifikaadiga*[@totaledu].

20. Psühromeeter.

21. Keemia: pipetid, spaatlid, täppiskaal, keeduklaasid, katseklaasid, filtrid, lehtrid, hoiupurgid, kummikindad eri suuruses, kaitseprillid.

22. 3D-printer.

23. Mehhaaniline elekter.

24. Petri tassid.

25. Rippkaal.

